### PR TITLE
Append custom classes

### PR DESCRIPTION
**Pull request by Matt-Butler**
https://github.com/cerner/terra-react-svg-loader/issues/4
Option 1

@cerner/terra

### CODE REVIEW

**Comment by bjankord** [comment]
Should we add test for Icon supports adding custom classes?

**Comment by Matt-Butler** [comment]
The `terra-react-svg-loader` provides the react component, but does not render the component.

In an application
```
import Scheduled from 'terra-icon/lib/icon/static/scheduled.svg'
```
the loader will return
```
import React from 'react';
import Icon from 'terra-icon';
import classNames from 'classnames';

const SvgIcon = customProps => {
  const attributes = Object.assign({}, customProps);
  attributes.className = classNames("terra-Icon", attributes.className);

  return (
    <Icon {...attributes}>
      <path d="M31 5V1.8c0-1-.8-1.8-1.8-1.8h-1.5c-1 0-1.8.8-1.8 1.8V5H11V1.8c0-1-.8-1.8-1.8-1.8H7.8C6.8 0 6 .8 6 1.8V5H2v33h19.1c-.1-.7-.1-1.3-.1-2v-1H5V17h27v4.6c1-.3 2-.4 3-.5V5h-4z" ></path><path fill="#78C346" d="M36 24c6.6 0 12 5.4 12 12s-5.4 12-12 12-12-5.4-12-12 5.4-12 12-12z" ></path><path fill="#FFF" d="M34.1 42.4l-6.5-6.5 2.1-2.1 4.4 4.3 8.2-8.1 2.1 2.1-10.3 10.3z" ></path>
    </Icon>
  )
};

SvgIcon.displayName = "scheduled";
SvgIcon.defaultProps = {"aria-hidden":"true","className":"terra-Icon","viewBox":"0 0 48 48","xmlns":"http://www.w3.org/2000/svg"};

export default SvgIcon;
```

In order to test custom classes, we need to render the component in the DOM. 

I wanted to have unit tests for this behavior in terra-Icon, but that is not possible either.  Terra-icon is dependent on using webpack loaders, so Jest is unable to render an Icon component.

The best I can do is add additional examples in terra-Icon to test this behavior: https://github.com/cerner/terra-icon/pull/15

**Comment by bjankord** [comment]
@Matt-Butler Ok sounds like this is something we may need to test with terra-toolkit.

**Comment by dkasper-was-taken** [comment]
+1

**Pull request merged**
